name: Deploy to AWS Lambda
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      # sam build 
      - run: |
	  sam validate
	  sam build --use-container --debug
	  sam package --profile --s3-bucket vidpit-authentication2 --output-template-file out.yml --region eu-central-1
	  sam deploy --profile vidpit --template-file out.yml --stack-name vidpit-authentication --region eu-central-1 --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM
